### ISSUE TITLE
SemaphoreFullException

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [ZeeLyn/Dapper.Extensions#13]
after executing this code _sometimes_ the error thrown

``` C#
await _connection.QueryAsync<GroupQuery>(sql: query, param: parameters, cacheKey: cacheKey.ToString());
```

**System.Threading.SemaphoreFullException
Adding the specified count to the semaphore would cause it to exceed its maximum count.**

**Comment by ZeeLyn** [comment]
This is a bug. When failed to obtain the lock, need to cache Fallback, but I haven't figured out how to achieve more elegance.

**Comment by ZeeLyn** [comment]
I decided to throw DapperCacheException because Dapper.Extensions is just an ORM library. If failed to acquire the lock, it means that your system has performance problems, so you need to implement cache [FALLBACK](https://github.com/App-vNext/Polly)  in your business code.
This issue will be resolved in the next version.

**Comment by ebrahimkhodadadi** [comment]
tnx I read some about the error but I didn't understand the exact reason that the error was thrown can u explain more

**Comment by ZeeLyn** [comment]
Sorry, I didn't describe it clearly. These are two questions.
1. SemaphoreFullException is a bug. Because the failure to acquire the lock is not handled, the Release() method is executed without acquiring the lock, so SemaphoreFullException is thrown.

2. To fix this bug, you need to add logic for failure to acquire locks. Failure to acquire locks means that there is a performance problem with the cache service or database service. For business code, FALLBACK processing needs to be done, but this belongs to business-level logic. And Dapper.Extensions is just an ORM library, it should not be mixed with business logic code, so I think I should throw an exception in this case (temporarily named DapperCacheException), capture this exception in the business code and do FALLBACK processing. This is the best solution I can think of so far, if you have a better way to handle it please tell me.

My English is not good, I hope I described it clearly.

**Comment by ebrahimkhodadadi** [comment]
isn't it better to use Semaphore instead of SemaphoreSlim? which it doesn't need to set maximum threads

**Comment by ZeeLyn** [comment]
I think this is not a question of whether Semaphore is better or SemaphoreSlim is better. This is a [Cache Penetration, Cache Breakdown, Cache Avalanche ](https://interviewnoodle.com/cache-problems-cache-penetration-cache-breakdown-cache-avalanche-9b866483e2b7)problem.
